name: PR pipeline
on:
  pull_request:

jobs:
  release:
    name: Build
    runs-on: ubuntu-24.04
    if: github.event.pull_request.draft == false
    steps:

      - name: Show toolchain version
        run: rustup show active-toolchain -v

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Run Clippy
        run: cargo clippy --no-deps -- -Dwarnings

      - name: Run rustfmt
        run: cargo fmt --check

      - name: Run rustdoc
        run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: "-D warnings"

      - name: Run tests
        run: GITLAB_HOSTNAME=hostname GITLAB_TOKEN=glpat-XXX OWNED_ENTITIES_ONLY=yes cargo test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Push docker image release
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          tags: cnieg/gitlab-tokens-exporter:latest
